### PR TITLE
little fixes for now

### PR DESCRIPTION
**Pull request by annihilatorrrr**

### CODE REVIEW

**Comment by jayantkageri** [comment]
looks it works, let divkix say something
& me can't go to tg as schedule is tight, so tag me in GitHub if you want anything from me

**Comment by annihilatorrrr** [comment]
> looks it works, let divkix say something
> & me can't go to tg as schedule is tight, so tag me in GitHub if you want anything from me

omk, chk mail after 1 min

**Review by Divkix — DISMISSED** [review]
Everything looks good, I'll just update the requirements

**Comment by Divkix** [comment]
Issue here:
```
File "<frozen importlib._bootstrap_external>", line 918, in source_to_code
2021-07-18T09:21:22.080997+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2021-07-18T09:21:22.081065+00:00 app[worker.1]:   File "/app/alita/plugins/rules.py", line 72
2021-07-18T09:21:22.081074+00:00 app[worker.1]:     ),
2021-07-18T09:21:22.081083+00:00 app[worker.1]:     ^
2021-07-18T09:21:22.081102+00:00 app[worker.1]: SyntaxError: positional argument follows keyword argument
2021-07-18T09:21:22.484624+00:00 app[worker.1]: make: *** [Makefile:12: run] Error 1
```

**Review by Divkix — CHANGES_REQUESTED** [review]
needs fix:

```
File "<frozen importlib._bootstrap_external>", line 918, in source_to_code
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/app/alita/plugins/rules.py", line 72
      ),
     ^
SyntaxError: positional argument follows keyword argument
make: *** [Makefile:12: run] Error 1
```

**Comment by annihilatorrrr** [comment]
> Issue here:
> 
> ```
> File "<frozen importlib._bootstrap_external>", line 918, in source_to_code
> 2021-07-18T09:21:22.080997+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> 2021-07-18T09:21:22.081065+00:00 app[worker.1]:   File "/app/alita/plugins/rules.py", line 72
> 2021-07-18T09:21:22.081074+00:00 app[worker.1]:     ),
> 2021-07-18T09:21:22.081083+00:00 app[worker.1]:     ^
> 2021-07-18T09:21:22.081102+00:00 app[worker.1]: SyntaxError: positional argument follows keyword argument
> 2021-07-18T09:21:22.484624+00:00 app[worker.1]: make: *** [Makefile:12: run] Error 1
> ```

Ig it's markdown part I escaped because it got little bugs there 
Oke will fix

**Comment by Divkix** [comment]
> > Issue here:
> > ```
> > File "<frozen importlib._bootstrap_external>", line 918, in source_to_code
> > 2021-07-18T09:21:22.080997+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> > 2021-07-18T09:21:22.081065+00:00 app[worker.1]:   File "/app/alita/plugins/rules.py", line 72
> > 2021-07-18T09:21:22.081074+00:00 app[worker.1]:     ),
> > 2021-07-18T09:21:22.081083+00:00 app[worker.1]:     ^
> > 2021-07-18T09:21:22.081102+00:00 app[worker.1]: SyntaxError: positional argument follows keyword argument
> > 2021-07-18T09:21:22.484624+00:00 app[worker.1]: make: *** [Makefile:12: run] Error 1
> > ```
> 
> Ig it's markdown part I escaped because it got little bugs there
> Oke will fix

yup

**Comment by annihilatorrrr** [comment]
shift to improvements

**Pull request closed without merging**
